workflows:
  android-apk-build:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 30
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Buat Otomatis File Gradlew yang Hilang
        script: |
          # Memaksa sistem membuat wrapper gradle versi standar Android terbaru
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
