workflows:
  android-apk-build:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 30
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Buat Otomatis File Gradlew Versi Terbaru
        script: |
          gradle wrapper --gradle-version 9.3.1
          chmod +x gradlew
      - name: Buat File Kunci Keamanan Otomatis
        script: |
          # Perintah untuk membuat file debug.keystore buatan di folder utama proyek
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
